import { User } from './models/userModel';
import { Product } from './models/productModel';
import bcrypt from 'bcryptjs';

export const sampleProducts: Product[] = [
  {
    name: 'plant1',
    slug: 'plant1',
    image: './p_image/p1.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant2',
    slug: 'plant2',
    image: './p_image/p2.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant3',
    slug: 'plant3',
    image: './p_image/p3.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant4',
    slug: 'plant4',
    image: './p_image/p4.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant5',
    slug: 'plant5',
    image: './p_image/p5.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant6',
    slug: 'plant6',
    image: './p_image/p6.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant7',
    slug: 'plant7',
    image: './p_image/p7.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant8',
    slug: 'plant8',
    image: './p_image/p8.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant9',
    slug: 'plant9',
    image: './p_image/p9.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant10',
    slug: 'plant10',
    image: './p_image/p10.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant11',
    slug: 'plant11',
    image: './p_image/p11.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant12',
    slug: 'plant12',
    image: './p_image/p12.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant13',
    slug: 'plant13',
    image: './p_image/p13.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant14',
    slug: 'plant14',
    image: './p_image/p14.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant15',
    slug: 'plant15',
    image: './p_image/p15.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant16',
    slug: 'plant16',
    image: './p_image/p16.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant17',
    slug: 'plant17',
    image: './p_image/p17.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant18',
    slug: 'plant18',
    image: './p_image/p18.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant19',
    slug: 'plant19',
    image: './p_image/p19.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant20',
    slug: 'plant20',
    image: './p_image/p20.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
  {
    name: 'plant21',
    slug: 'plant21',
    image: './p_image/p21.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
    images: [],
    isFeatured: false,
  },
];

export const sampleUsers: User[] = [
  {
    name: 'bharathviswa',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: true,
  },
  {
    name: 'user1',
    email: 'user@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: false,
  },
];
