import { Product } from './types/Product';

export const sampleProducts: Product[] = [
  {
    name: 'plant1',
    slug: 'plant1',
    image: 'p1.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant2',
    slug: 'plant2',
    image: './p_img/p2.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant3',
    slug: 'plant3',
    image: './p_img/p3.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant4',
    slug: 'plant4',
    image: './p_img/p4.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant5',
    slug: 'plant5',
    image: './p_img/p5.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant6',
    slug: 'plant6',
    image: './p_img/p6.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant7',
    slug: 'plant7',
    image: './p_img/p7.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant8',
    slug: 'plant8',
    image: './p_img/p8.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant9',
    slug: 'plant9',
    image: './p_img/p9.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant10',
    slug: 'plant10',
    image: './p_img/p10.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant11',
    slug: 'plant11',
    image: './p_img/p11.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant12',
    slug: 'plant12',
    image: './p_img/p12.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant13',
    slug: 'plant13',
    image: './p_img/p13.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant14',
    slug: 'plant14',
    image: './p_img/p14.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant15',
    slug: 'plant15',
    image: 'p15.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant16',
    slug: 'plant16',
    image: 'p16.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant17',
    slug: 'plant17',
    image: 'p17.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant18',
    slug: 'plant18',
    image: 'p18.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant19',
    slug: 'plant19',
    image: 'p19.png',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant20',
    slug: 'plant20',
    image: 'p20.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
  {
    name: 'plant21',
    slug: 'plant21',
    image: 'p21.jpg',
    categories: 'sacullent',
    brand: 'NB',
    price: 350,
    countInStock: 100,
    description: 'dry plant, no watering, weather tolerant, zero maintenance',
    rating: 4.5,
    numReviews: 3,
  },
];
